In [3]:
import numpy as np

In [3]:
# ARITHMETIC OPERATIONS

In [16]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [17]:
a1

array([1, 2, 3, 4, 5])

In [18]:
a2

array([ 6,  7,  8,  9, 10])

In [19]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [20]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [21]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [22]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [23]:
a1 // a2

array([0, 0, 0, 0, 0])

In [24]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [37]:
arr2 = np.arange(1, 37).reshape(6, 6)

In [38]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [39]:
arr2 + 10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46]])

In [40]:
# BROADCASTING

In [41]:
arr = np.arange(1, 11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
broadcast = arr + 10

In [44]:
broadcast

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr +10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [49]:
# DEEP AND SHALOW COPY

In [50]:
arr = np.arange(1, 21)

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
slice = arr[:5]

In [57]:
slice

array([1, 2, 3, 4, 5])

In [59]:
slice = slice * 10

In [60]:
slice

array([10, 20, 30, 40, 50])

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
a = arr

In [63]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
a[0] = 100

In [66]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [67]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [68]:
b = a.copy()

In [69]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [70]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [71]:
b[0] = 1

In [72]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [1]:
# MATRIX OPERATIONS

In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [5]:
a

array([[1, 2],
       [3, 4]])

In [6]:
b

array([[5, 6],
       [7, 8]])

In [7]:
a * b

array([[ 5, 12],
       [21, 32]])

In [8]:
a @ b

array([[19, 22],
       [43, 50]])

In [9]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
a.T

array([[1, 3],
       [2, 4]])

In [12]:
# ADVANCE ARRAY MANIPULATION

In [13]:
# Stacking Array

In [14]:
a = np.array([1, 2, 3, 4])

In [15]:
b = np.array([5, 6, 7, 8])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
b

array([5, 6, 7, 8])

In [18]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [21]:
np.row_stack((a,b))

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11240\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
# Splitting Array

In [23]:
arr = np.arange(16).reshape(4, 4)

In [24]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.hsplit(arr,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [26]:
np.hsplit(arr,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [28]:
a = np.vsplit(arr,2)

In [31]:
a = np.vsplit(arr,4)

In [32]:
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [33]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
