In [ ]:
# NUMPY INDEXING AND SLICING OF VECTORS

In [ ]:
import numpy as np

In [6]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[6]

np.int64(17)

In [8]:
arr1 = arr[1:5]
arr1

array([12, 13, 14, 15])

In [9]:
arr1 = arr[:5]
arr1

array([11, 12, 13, 14, 15])

In [10]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[3::2]

array([14, 16, 18, 20])

In [12]:
# NUMPY INDEXING AND SLICING OF MATRIX

In [14]:
arr= np.arange(1, 31).reshape(6, 5)

In [15]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr[0]

array([1, 2, 3, 4, 5])

In [17]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [18]:
arr[5]

array([26, 27, 28, 29, 30])

In [19]:
arr[0][2]

np.int64(3)

In [20]:
arr[0][0]

np.int64(1)

In [21]:
arr[0, 0]

np.int64(1)

In [22]:
arr[0, 4]

np.int64(5)

In [23]:
arr[5, 4]

np.int64(30)

In [29]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [28]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [33]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

In [34]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
arr[2:, 2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [36]:
arr[2:, :4]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24],
       [26, 27, 28, 29]])

In [37]:
arr[:, 3]

array([ 4,  9, 14, 19, 24, 29])

In [38]:
# BOOLEAN INDEXING

In [46]:
arr = np.arange(11, 21)

In [47]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
bool_idx = arr % 2 == 0

In [49]:
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [50]:
arr = arr[bool_idx]
arr

array([12, 14, 16, 18, 20])