In [1]:
import numpy as np

**Valid Sudoku**

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
b = np.sum(s,axis=1)

In [4]:
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("for rows sudoku is valid")

for rows sudoku is valid


In [6]:
c = np.sum(s, axis=0)

In [7]:
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [8]:
for i in c:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("for columns sudoku is valid")

for columns sudoku is valid


In [9]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [10]:
sl = s[:3,:3]

In [11]:
sl

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [12]:
sl = s[0:3, 3:6]

In [13]:
sl

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [14]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [15]:
**General Questions**

SyntaxError: invalid syntax (1562188386.py, line 1)

In [17]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

In [ ]:
#Find the average age of students.
a = data[0:, :1]

In [ ]:
np.mean(a)

In [ ]:
#Extract Math marks of all students.
m = data[:, 1:2]
m

In [ ]:
#Find the highest Science mark.
sm = data[:, 2:]
np.max(sm)

In [ ]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]


In [ ]:
#Increase Math marks of all students by 5.
data = data[:,1] += 5
data

In [ ]:
#Find how many students are younger than 19.
age = data[:,0] < 19
len(data[age])

In [ ]:
#Calculate the average marks in each subject (column-wise mean).
data
np.mean(data[:,1:], axis=0)
data

In [ ]:
#Get data of students who scored at least 80 in both subjects.
sd = data[(data[:,1] >= 80) & (data[:,2] >= 80)]
sd

In [ ]:
data

In [18]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])